#!/usr/bin/env bash
# Using if and else to check information about a file
file="school"

if [ -s "$file" ]; then
	echo "school file exists"
else
	echo "school file does not exist"
fi

if [ -z "$file" ]; then
	echo "school file is empty"
else
	echo "school file is not empty"
fi

if [ -f "$file" ]; then
	echo "school is a regular file"
else
	echo " "
fi
